/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorPanelInicio;
import Modelo.ModeloPanelInicial;

/**
 *
 * @author axels
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
        Modelo.ModeloPanelInicial modelo = new ModeloPanelInicial(this);
        Controlador.ControladorPanelInicio controlador = new ControladorPanelInicio(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn3 = new javax.swing.JPanel();
        a2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        a1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Degradado = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        a2.setForeground(new java.awt.Color(51, 51, 51));
        a2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2.setText("Hola 3");
        btn3.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn3.png"))); // NOI18N
        btn3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 200, 120));

        btn2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1.setText("Hola 2");
        btn2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn2.png"))); // NOI18N
        btn2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 200, 120));

        btn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a.setText("Hola");
        btn1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn1.png"))); // NOI18N
        btn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 200, 120));

        Degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DegradadoNegro.png"))); // NOI18N
        add(Degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPanel1.png"))); // NOI18N
        add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPanel2.png"))); // NOI18N
        add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPanel3.png"))); // NOI18N
        add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Degradado;
    public javax.swing.JLabel Fondo1;
    public javax.swing.JLabel Fondo2;
    public javax.swing.JLabel Fondo3;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    public javax.swing.JPanel btn1;
    public javax.swing.JPanel btn2;
    public javax.swing.JPanel btn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorPanelInicio controlador){
        
        btn1.addMouseListener(controlador);
        btn2.addMouseListener(controlador);
        btn3.addMouseListener(controlador);
        
    }
}
