/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;


import Controlador.ControladorVistaPrincipal;
import Modelo.ModeloVistaPrincipal;


/**
 *
 * @author axels
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        Modelo.ModeloVistaPrincipal modelo = new ModeloVistaPrincipal(this);
        Controlador.ControladorVistaPrincipal controlador = new ControladorVistaPrincipal(modelo);

        setControlador(controlador);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        PanelMenuVertical = new javax.swing.JPanel();
        btnInicio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        PanelFondoMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescripcionProblema = new javax.swing.JTextArea();
        btn3 = new javax.swing.JPanel();
        bordeBtn3 = new javax.swing.JLabel();
        lbBtn3 = new javax.swing.JLabel();
        lbBtn3Degradado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        bordeBtn2 = new javax.swing.JLabel();
        lbBtn2 = new javax.swing.JLabel();
        lbBtn2Degradado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JPanel();
        bordeBtn1 = new javax.swing.JLabel();
        lbBtn1 = new javax.swing.JLabel();
        lbBtn1Degradado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Degradado = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenuVertical.setBackground(new java.awt.Color(51, 51, 51));
        PanelMenuVertical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnInicio.png"))); // NOI18N
        btnInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        PanelMenuVertical.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 50, 50));

        FondoPanel.add(PanelMenuVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 720));

        PanelFondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INGRESE LA DESCRIPCIÓN DEL PROBLEMA A RESOLVER");
        PanelFondoMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 560, 40));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        txtaDescripcionProblema.setBackground(new java.awt.Color(255, 255, 255));
        txtaDescripcionProblema.setColumns(20);
        txtaDescripcionProblema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtaDescripcionProblema.setLineWrap(true);
        txtaDescripcionProblema.setRows(5);
        txtaDescripcionProblema.setWrapStyleWord(true);
        txtaDescripcionProblema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        txtaDescripcionProblema.setOpaque(false);
        jScrollPane2.setViewportView(txtaDescripcionProblema);

        PanelFondoMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 990, 160));

        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordeBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 196, 0), 2));
        btn3.add(bordeBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        lbBtn3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbBtn3.setForeground(new java.awt.Color(255, 255, 255));
        lbBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtn3.setText("<html>\n<div style=\"text-align:center;\">\nLey <br>\nMultiplicativa\n</div>\n</html>");
        btn3.add(lbBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        lbBtn3Degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonDegradado.png"))); // NOI18N
        lbBtn3Degradado.setText("jLabel4");
        btn3.add(lbBtn3Degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBtn3.png"))); // NOI18N
        btn3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        PanelFondoMenu.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 200, 120));

        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordeBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 196, 0), 2));
        btn2.add(bordeBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));
        btn2.add(lbBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        lbBtn2Degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonDegradado.png"))); // NOI18N
        btn2.add(lbBtn2Degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBtn2.png"))); // NOI18N
        btn2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelFondoMenu.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 200, 120));

        btn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bordeBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 196, 0), 2));
        btn1.add(bordeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        lbBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbBtn1.setForeground(new java.awt.Color(255, 255, 255));
        lbBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtn1.setText("Hola");
        btn1.add(lbBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        lbBtn1Degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonDegradado.png"))); // NOI18N
        btn1.add(lbBtn1Degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn1.png"))); // NOI18N
        btn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        PanelFondoMenu.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 200, 120));

        btnAceptar.setBackground(new java.awt.Color(74, 144, 226));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(74, 144, 226));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ACEPTAR");
        btnAceptar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        PanelFondoMenu.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 200, 50));

        Degradado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DegradadoNegro.png"))); // NOI18N
        PanelFondoMenu.add(Degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo1.setBackground(new java.awt.Color(245, 245, 220));
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.png"))); // NOI18N
        Fondo1.setOpaque(true);
        PanelFondoMenu.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoProbabilidadCondicional.png"))); // NOI18N
        PanelFondoMenu.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLeyMultiplicativa.png"))); // NOI18N
        PanelFondoMenu.add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FondoPanel.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1230, 720));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        FondoPanel.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(FondoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Degradado;
    private javax.swing.JLabel Fondo;
    public javax.swing.JLabel Fondo1;
    public javax.swing.JLabel Fondo2;
    public javax.swing.JLabel Fondo3;
    private javax.swing.JPanel FondoPanel;
    public javax.swing.JPanel PanelFondoMenu;
    private javax.swing.JPanel PanelMenuVertical;
    public javax.swing.JLabel bordeBtn1;
    public javax.swing.JLabel bordeBtn2;
    public javax.swing.JLabel bordeBtn3;
    public javax.swing.JPanel btn1;
    public javax.swing.JPanel btn2;
    public javax.swing.JPanel btn3;
    public javax.swing.JPanel btnAceptar;
    public javax.swing.JPanel btnInicio;
    public javax.swing.JPanel contenedor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbBtn1;
    public javax.swing.JLabel lbBtn1Degradado;
    public javax.swing.JLabel lbBtn2;
    public javax.swing.JLabel lbBtn2Degradado;
    public javax.swing.JLabel lbBtn3;
    public javax.swing.JLabel lbBtn3Degradado;
    public javax.swing.JTextArea txtaDescripcionProblema;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaPrincipal controlador){
        this.addWindowListener(controlador);
        btn1.addMouseListener(controlador);
        btn2.addMouseListener(controlador);
        btn3.addMouseListener(controlador);
        btnInicio.addMouseListener(controlador);
        btnAceptar.addMouseListener(controlador);
    }
    
//    public void setControlador2(ControladorVistaPrincipal controlador2){
//        
//    }
}
